[project]
name = "spec_parser"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4[html5lib]==4.15.0",
    "requests==2.34.2",
]

[project.scripts]
parse = "spec_parser.parser:parse"

[dependency-groups]
dev = [
    "mypy==2.3.0",
    "ruff==0.16.1",
    "types-requests==2.33.0.20260712",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.mypy]
python_version = "3.10"
strict = true

# Disallow dynamic typing
#disallow_any_unimported = true
#disallow_any_expr = true
disallow_any_decorated = true
disallow_any_explicit = true

show_error_codes = true
warn_unreachable = true


[tool.ruff.lint]
extend-select = [
    "A",     # flake8-builtins
    "ANN",   # flake8-annotations
    "ARG",   # flake8-unused-arguments
    "EM",    # flake8-errmsg
    "INP",   # flake8-no-pep420
    "RSE",   # flake8-raise
    "SLF",   # flake8-self
    "TID",   # flake8-tidy-imports
]
ignore = [
    "A003",  # builtin-attribute-shadowing
]
fixable = [
    "I",     # isort
    "F401",  # unused-import
    "TC",    # flake8-type-checking
    "TID",   # flake8-tidy-imports
    "UP",    # pyupgrade
]
dummy-variable-rgx = "^_$"

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
split-on-trailing-comma = false
