name: spec_parser

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spec_parser
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Get full Python version
        id: full-python-version
        run: echo ::set-output name=version::$(python -c "import sys; print('.'.join(str(x) for x in sys.version_info))")
      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        with:
          path: .venv
          key: lint-poetry-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: lint-poetry-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-
      - name: Install Poetry
        run: pip install poetry
      - name: Setup the virtual environment
        run: poetry config --local virtualenvs.in-project true
      - name: Install or upgrade dependencies
        run: poetry install --remove-untracked
      - name: Check import order
        run: poetry run poe isort-check
      - name: Check formatting using black
        run: poetry run poe black-check
      - name: Test with mypy
        run: poetry run poe mypy
      - name: Test with pylint
        run: poetry run poe pylint
